### ISSUE TITLE
Update Svelte Dependency to Version 4.0.0 or Higher

### ISSUE THREAD

**Issue by ptavarez** [ballercat/jambox#58]
### Description
We are trying to upgrade from Storybook 6 to Storybook 8 in `sf-ui-web` and encountered an issue with JamBox's Svelte dependency. Storybook 8 requires Svelte version 4, but JamBox is currently using Svelte version 3.

### Error
![Screenshot 2024-07-31 at 2 54 06 PM](https://github.com/user-attachments/assets/81f0257e-a404-4367-b95a-3b2c6d0dd1e4)

### Request
Please update the Svelte dependency in JamBox to version 4.0.0 or higher to ensure compatibility with Storybook 8.

#### Thank you!

**Comment by ptavarez** [comment]
I could spin up a PR for this! Just let me know what would be most helpful 😄

**Comment by ballercat** [comment]
Okay no problem. I can probably get to that today.

**Comment by ptavarez** [comment]
Sweet, thank you!

**Comment by ballercat** [comment]
https://github.com/ballercat/jambox/pull/59

This will do it... Please be aware that there is a nasty bug in Cypress 13.x (which I had to upgrade to) which causes it to no longer find a devServer for component tests. I had to disable cypress checks in CI in order to get it actually to build. I suspect it's something to do with it no longer accurately handling proxied requests.

https://github.com/cypress-io/cypress/issues/27990

**Comment by ballercat** [comment]
Version `0.4.2` was published
